---
slug: barfing-rainbow
filename: barfing-rainbow
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: a67f168c-e417-4621-8498-467472696f53
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
